[package]
name = "gachix"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20"
clap = { version = "4.5.48", features = ["derive"] }
nix-base32 = "0.2.0"
sha2 = "0.10.9"
nix-nar = "0.3.0"
actix-web = "4.11.0"
tracing = "0.1.41"
tracing-actix-web = "0.7.19"
tracing-subscriber = "0.3.20"
